// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParksApi.Models;

#nullable disable

namespace ParksApi.Migrations
{
    [DbContext(typeof(ParksApiContext))]
    [Migration("20231027215902_AddSeedData")]
    partial class AddSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ParksApi.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CampingAllowed")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("DogsAllowed")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("FeeRequired")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            CampingAllowed = "yes",
                            Description = "Crater Lake inspires awe.",
                            DogsAllowed = "yes",
                            FeeRequired = "yes",
                            Name = "Crater Lake",
                            Status = "open"
                        },
                        new
                        {
                            ParkId = 2,
                            CampingAllowed = "yes",
                            Description = "No agates, but a great place to see the sunset.",
                            DogsAllowed = "yes",
                            FeeRequired = "no",
                            Name = "Agate Beach State Recreation Site",
                            Status = "open"
                        },
                        new
                        {
                            ParkId = 3,
                            CampingAllowed = "yes",
                            Description = "This park has great birdwatching and tidepools to explore.",
                            DogsAllowed = "yes",
                            FeeRequired = "no",
                            Name = "Fogarty Creek State Recreation Area",
                            Status = "open"
                        },
                        new
                        {
                            ParkId = 4,
                            CampingAllowed = "no",
                            Description = "Eons of acidic water seeping into marble rock created and decorated these wondrous marble halls.",
                            DogsAllowed = "no",
                            FeeRequired = "yes",
                            Name = "Oregon Caves National Monument",
                            Status = "closed"
                        },
                        new
                        {
                            ParkId = 5,
                            CampingAllowed = "no",
                            Description = "Colorful rock formations preserve a world class record of plant and animal evolution, changing climate, and past ecosystems that span over 40 million years.",
                            DogsAllowed = "no",
                            FeeRequired = "no",
                            Name = "John Day Fossil Beds National Monument",
                            Status = "open"
                        },
                        new
                        {
                            ParkId = 6,
                            CampingAllowed = "yes",
                            Description = "This convergence of three geologically distinct mountain ranges has resulted in an area with unparalleled biological diversity and a tremendously varied landscape.",
                            DogsAllowed = "yes",
                            FeeRequired = "no",
                            Name = "Cascade-Siskiyou National Monument",
                            Status = "open"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
